apiVersion: v1
kind: Service
metadata:
  name: catsrc-deppy-adapter
  namespace: olm
spec:
  type: NodePort
  ports:
  - name: grpc
    port: 50052
    protocol: TCP
    targetPort: 50052
  selector:
    olm.deppyadapter.catalogsource: community-operators
